import { Bill, BillCategory, NotificationItem, UserProfile } from '../types';

export const CATEGORY_CONFIG: Record<
  BillCategory,
  { label: string; icon: string; color: string; bgLight: string; border: string; providerExamples: string }
> = {
  electricity: {
    label: 'Electricity',
    icon: 'Zap',
    color: 'text-amber-600 dark:text-amber-400',
    bgLight: 'bg-amber-50 dark:bg-amber-950/40',
    border: 'border-amber-200 dark:border-amber-800/50',
    providerExamples: 'LESCO, K-Electric, FESCO, IESCO',
  },
  gas: {
    label: 'Gas',
    icon: 'Flame',
    color: 'text-orange-600 dark:text-orange-400',
    bgLight: 'bg-orange-50 dark:bg-orange-950/40',
    border: 'border-orange-200 dark:border-orange-800/50',
    providerExamples: 'SNGPL, SSGC',
  },
  internet: {
    label: 'Internet',
    icon: 'Wifi',
    color: 'text-teal-600 dark:text-teal-400',
    bgLight: 'bg-teal-50 dark:bg-teal-950/40',
    border: 'border-teal-200 dark:border-teal-800/50',
    providerExamples: 'PTCL Flash Fiber, StormFiber, Nayatel',
  },
  water: {
    label: 'Water',
    icon: 'Droplet',
    color: 'text-sky-600 dark:text-sky-400',
    bgLight: 'bg-sky-50 dark:bg-sky-950/40',
    border: 'border-sky-200 dark:border-sky-800/50',
    providerExamples: 'WASA Lahore, KWSB, CDA Water',
  },
  hospital: {
    label: 'Medical',
    icon: 'HeartPulse',
    color: 'text-rose-600 dark:text-rose-400',
    bgLight: 'bg-rose-50 dark:bg-rose-950/40',
    border: 'border-rose-200 dark:border-rose-800/50',
    providerExamples: 'Shaukat Khanum, Doctors Hospital, Chughtai Lab',
  },
  retail: {
    label: 'Mobile',
    icon: 'ShoppingBag',
    color: 'text-indigo-600 dark:text-indigo-400',
    bgLight: 'bg-indigo-50 dark:bg-indigo-950/40',
    border: 'border-indigo-200 dark:border-indigo-800/50',
    providerExamples: 'Jazz Postpaid, Zong 4G, Telenor, Ufone',
  },
  insurance: {
    label: 'Insurance',
    icon: 'Shield',
    color: 'text-purple-600 dark:text-purple-400',
    bgLight: 'bg-purple-50 dark:bg-purple-950/40',
    border: 'border-purple-200 dark:border-purple-800/50',
    providerExamples: 'State Life, EFU General, Property Tax',
  },
  other: {
    label: 'Other',
    icon: 'FileText',
    color: 'text-slate-600 dark:text-slate-400',
    bgLight: 'bg-slate-50 dark:bg-slate-900/40',
    border: 'border-slate-200 dark:border-slate-800',
    providerExamples: 'General Maintenance, Society Dues',
  },
};

export const INITIAL_USER_PROFILE: UserProfile = {
  name: '',
  email: '',
  currentHealthScore: 0,
  onboardingCompleted: true,
  currency: 'PKR',
  preferences: {
    darkMode: 'light',
    notifications: {
      anomalyAlerts: true,
      reminders: true,
      tips: true,
      weeklySummary: true,
    },
  },
};

export const DEMO_BILLS_ARCHIVE: Bill[] = [
  {
    id: 'bill-lesco-001',
    category: 'electricity',
    providerName: 'LESCO (Lahore Electric Supply)',
    accountNumberMasked: '•••• 8921',
    billDate: '2026-07-12',
    dueDate: '2026-07-28',
    billingPeriodStart: '2026-06-10',
    billingPeriodEnd: '2026-07-10',
    totalAmount: 28450.00,
    currency: 'PKR',
    currencySymbol: 'Rs.',
    hasAnomaly: true,
    anomalyCount: 1,
    status: 'analyzed',
    createdAt: '2026-07-12T10:15:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=600',
    lineItems: [
      {
        id: 'li-1',
        name: 'Variable Energy Charge (520 Units @ Peak/Off-Peak)',
        amount: 19760.00,
        type: 'base_charge',
        explanation: 'Electricity units consumed across protected/unprotected slabs.',
        isAnomaly: false,
      },
      {
        id: 'li-2',
        name: 'Fuel Price Adjustment (FPA) Surcharge',
        amount: 4120.00,
        type: 'fee',
        explanation: 'Monthly fuel cost correction adjustment passed by NEPRA.',
        isAnomaly: true,
        anomalyReason: 'This FPA rate is 32% higher than previous month billing cycle.',
      },
      {
        id: 'li-3',
        name: 'Electricity Duty & PTV Fee',
        amount: 450.00,
        type: 'tax',
        explanation: 'Standard provincial electricity duty and fixed state broadcast fee.',
        isAnomaly: false,
      },
      {
        id: 'li-4',
        name: 'General Sales Tax (GST 18%)',
        amount: 4120.00,
        type: 'tax',
        explanation: 'Federal GST applied on total power consumption and surcharges.',
        isAnomaly: false,
      },
    ],
    aiAnalysis: {
      plainSummary:
        'Your LESCO bill is ₨ 28,450 this month. Consumption is 520 units. A significant portion (₨ 4,120) comes from Fuel Price Adjustment (FPA) surcharges.',
      lineItems: [
        {
          id: 'li-1',
          name: 'Variable Energy Charge (520 Units @ Peak/Off-Peak)',
          amount: 19760.00,
          type: 'base_charge',
          explanation: 'Electricity units consumed across protected/unprotected slabs.',
          isAnomaly: false,
        },
        {
          id: 'li-2',
          name: 'Fuel Price Adjustment (FPA) Surcharge',
          amount: 4120.00,
          type: 'fee',
          explanation: 'Monthly fuel cost correction adjustment passed by NEPRA.',
          isAnomaly: true,
          anomalyReason: 'This FPA rate is 32% higher than previous month billing cycle.',
        },
        {
          id: 'li-3',
          name: 'Electricity Duty & PTV Fee',
          amount: 450.00,
          type: 'tax',
          explanation: 'Standard provincial electricity duty and fixed state broadcast fee.',
          isAnomaly: false,
        },
        {
          id: 'li-4',
          name: 'General Sales Tax (GST 18%)',
          amount: 4120.00,
          type: 'tax',
          explanation: 'Federal GST applied on total power consumption and surcharges.',
          isAnomaly: false,
        },
      ],
      totals: {
        subtotal: 19760.00,
        taxesAndFees: 8690.00,
        total: 28450.00,
      },
      comparison: {
        vsPreviousSummary: 'Bill increased by ₨ 3,850 (+15.6%) compared to June (₨ 24,600).',
        percentChange: 15.6,
        primaryDriver: 'Increased air conditioning usage during 5 PM – 11 PM peak tariff hours.',
        previousBillTotal: 24600.00,
        previousBillDate: '2026-06-12',
      },
      financialHealthScore: {
        score: 84,
        label: 'Good',
        factors: [
          { label: 'Slab tier management', impact: -10, description: 'Exceeded 500 unit threshold triggering non-protected tariff slab.' },
          { label: 'Timely payment record', impact: 12, description: 'Zero late payment surcharge incurred over 12 months.' },
        ],
      },
      savingsSuggestions: [
        {
          id: 's-1',
          title: 'Shift Inverter AC load during Peak Hours (5 PM - 11 PM)',
          detail: 'Setting AC to 26°C between 5 PM and 11 PM keeps consumption below 500 units slab, saving up to ₨ 4,200/month.',
          estimatedMonthlySavings: 4200.00,
          categoryRelevance: 'electricity',
          status: 'new',
        },
        {
          id: 's-2',
          title: 'Solar Net Metering Feasibility',
          detail: 'Your average 500+ unit consumption makes a 5kW Solar system ROI less than 2.2 years in Lahore region.',
          estimatedMonthlySavings: 21000.00,
          categoryRelevance: 'electricity',
          status: 'new',
        },
      ],
      disclaimer: 'This is an AI-generated bill breakdown for informational guidance. Tariff rates governed by NEPRA.',
    },
  },
  {
    id: 'bill-sngpl-002',
    category: 'gas',
    providerName: 'SNGPL (Sui Northern Gas)',
    accountNumberMasked: '•••• 4310',
    billDate: '2026-07-08',
    dueDate: '2026-07-25',
    billingPeriodStart: '2026-06-05',
    billingPeriodEnd: '2026-07-05',
    totalAmount: 4820.00,
    currency: 'PKR',
    currencySymbol: 'Rs.',
    hasAnomaly: false,
    anomalyCount: 0,
    status: 'analyzed',
    createdAt: '2026-07-08T14:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&q=80&w=600',
    lineItems: [
      {
        id: 'li-g1',
        name: 'Gas Consumption (1.4 HM3)',
        amount: 3200.00,
        type: 'base_charge',
        explanation: 'Natural gas usage billed under domestic tier slab.',
        isAnomaly: false,
      },
      {
        id: 'li-g2',
        name: 'Fixed Monthly Meter Rent',
        amount: 500.00,
        type: 'fee',
        explanation: 'Standard SNGPL meter rental and line upkeep charges.',
        isAnomaly: false,
      },
      {
        id: 'li-g3',
        name: 'GST (18%) & Sales Tax Surcharge',
        amount: 1120.00,
        type: 'tax',
        explanation: 'Government taxes applicable on gas charges and fixed charges.',
        isAnomaly: false,
      },
    ],
    aiAnalysis: {
      plainSummary:
        'Your SNGPL Sui Gas bill is ₨ 4,820 for July. Consumption is moderate within the 2nd domestic billing slab.',
      lineItems: [
        {
          id: 'li-g1',
          name: 'Gas Consumption (1.4 HM3)',
          amount: 3200.00,
          type: 'base_charge',
          explanation: 'Natural gas usage billed under domestic tier slab.',
          isAnomaly: false,
        },
        {
          id: 'li-g2',
          name: 'Fixed Monthly Meter Rent',
          amount: 500.00,
          type: 'fee',
          explanation: 'Standard SNGPL meter rental and line upkeep charges.',
          isAnomaly: false,
        },
        {
          id: 'li-g3',
          name: 'GST (18%) & Sales Tax Surcharge',
          amount: 1120.00,
          type: 'tax',
          explanation: 'Government taxes applicable on gas charges and fixed charges.',
          isAnomaly: false,
        },
      ],
      totals: {
        subtotal: 3200.00,
        taxesAndFees: 1620.00,
        total: 4820.00,
      },
      comparison: {
        vsPreviousSummary: 'Decreased by ₨ 980 (-16.9%) compared to June gas consumption.',
        percentChange: -16.9,
        primaryDriver: 'Lower water heating load during summer months.',
        previousBillTotal: 5800.00,
        previousBillDate: '2026-06-08',
      },
      financialHealthScore: {
        score: 92,
        label: 'Excellent',
        factors: [
          { label: 'Slab optimization', impact: 10, description: 'Gas volume maintained comfortably inside protected slab.' },
        ],
      },
      savingsSuggestions: [
        {
          id: 's-g1',
          title: 'Switch to Solar Water Heater before winter',
          detail: 'Installing a solar geyser reduces winter gas bill spikes by up to 70%.',
          estimatedMonthlySavings: 3500.00,
          categoryRelevance: 'gas',
          status: 'new',
        },
      ],
      disclaimer: 'This is an AI-generated analysis for informational purposes only.',
    },
  },
  {
    id: 'bill-ptcl-003',
    category: 'internet',
    providerName: 'PTCL Flash Fiber',
    accountNumberMasked: '•••• 1102',
    billDate: '2026-07-01',
    dueDate: '2026-07-18',
    billingPeriodStart: '2026-07-01',
    billingPeriodEnd: '2026-07-31',
    totalAmount: 3750.00,
    currency: 'PKR',
    currencySymbol: 'Rs.',
    hasAnomaly: false,
    anomalyCount: 0,
    status: 'analyzed',
    createdAt: '2026-07-01T09:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=600',
    lineItems: [
      {
        id: 'li-pt1',
        name: 'Flash Fiber 50 Mbps Unlimited Package',
        amount: 2999.00,
        type: 'base_charge',
        explanation: 'Monthly high-speed fiber internet subscription.',
        isAnomaly: false,
      },
      {
        id: 'li-pt2',
        name: 'Optical Network Terminal (ONT) Device Rental',
        amount: 250.00,
        type: 'fee',
        explanation: 'Monthly fiber router device leasing fee.',
        isAnomaly: false,
      },
      {
        id: 'li-pt3',
        name: 'Provincial Sales Tax (PST 19.5%)',
        amount: 501.00,
        type: 'tax',
        explanation: 'Telecom services PST mandated by Punjab Revenue Authority.',
        isAnomaly: false,
      },
    ],
    aiAnalysis: {
      plainSummary:
        'Your PTCL Flash Fiber bill is ₨ 3,750 for July. Rate is stable and consistent with your 50 Mbps package contract.',
      lineItems: [
        {
          id: 'li-pt1',
          name: 'Flash Fiber 50 Mbps Unlimited Package',
          amount: 2999.00,
          type: 'base_charge',
          explanation: 'Monthly high-speed fiber internet subscription.',
          isAnomaly: false,
        },
        {
          id: 'li-pt2',
          name: 'Optical Network Terminal (ONT) Device Rental',
          amount: 250.00,
          type: 'fee',
          explanation: 'Monthly fiber router device leasing fee.',
          isAnomaly: false,
        },
        {
          id: 'li-pt3',
          name: 'Provincial Sales Tax (PST 19.5%)',
          amount: 501.00,
          type: 'tax',
          explanation: 'Telecom services PST mandated by Punjab Revenue Authority.',
          isAnomaly: false,
        },
      ],
      totals: {
        subtotal: 2999.00,
        taxesAndFees: 751.00,
        total: 3750.00,
      },
      comparison: {
        vsPreviousSummary: 'Identical to June bill (₨ 3,750). Zero variance.',
        percentChange: 0,
        primaryDriver: 'Fixed contractual plan.',
        previousBillTotal: 3750.00,
        previousBillDate: '2026-06-01',
      },
      financialHealthScore: {
        score: 95,
        label: 'Excellent',
        factors: [
          { label: 'Consistent monthly fee', impact: 10, description: 'No unverified VAS or extra downloads charged.' },
        ],
      },
      savingsSuggestions: [
        {
          id: 's-pt1',
          title: 'Upgrade to Annual Upfront Payment Plan',
          detail: 'Pay 10 months upfront to get 2 months free PTCL Flash Fiber subscription (Save ₨ 7,500/yr).',
          estimatedMonthlySavings: 625.00,
          categoryRelevance: 'internet',
          status: 'new',
        },
      ],
      disclaimer: 'AI-generated analysis for PTCL broadband billing.',
    },
  },
  {
    id: 'bill-wasa-004',
    category: 'water',
    providerName: 'WASA Lahore',
    accountNumberMasked: '•••• 9931',
    billDate: '2026-07-03',
    dueDate: '2026-07-22',
    billingPeriodStart: '2026-05-01',
    billingPeriodEnd: '2026-06-30',
    totalAmount: 1850.00,
    currency: 'PKR',
    currencySymbol: 'Rs.',
    hasAnomaly: false,
    anomalyCount: 0,
    status: 'analyzed',
    createdAt: '2026-07-03T11:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1527016021513-b09758b777bd?auto=format&fit=crop&q=80&w=600',
    lineItems: [
      {
        id: 'li-w1',
        name: 'Bi-Monthly Water Supply Charges (10 Marla Plot)',
        amount: 1400.00,
        type: 'base_charge',
        explanation: 'Water supply rate according to property size category.',
        isAnomaly: false,
      },
      {
        id: 'li-w2',
        name: 'Sewerage & Drainage Maintenance Surcharge',
        amount: 450.00,
        type: 'fee',
        explanation: 'Monsoon drainage channel maintenance fee.',
        isAnomaly: false,
      },
    ],
    aiAnalysis: {
      plainSummary:
        'Your WASA Lahore bi-monthly water & drainage bill is ₨ 1,850.',
      lineItems: [
        {
          id: 'li-w1',
          name: 'Bi-Monthly Water Supply Charges (10 Marla Plot)',
          amount: 1400.00,
          type: 'base_charge',
          explanation: 'Water supply rate according to property size category.',
          isAnomaly: false,
        },
        {
          id: 'li-w2',
          name: 'Sewerage & Drainage Maintenance Surcharge',
          amount: 450.00,
          type: 'fee',
          explanation: 'Monsoon drainage channel maintenance fee.',
          isAnomaly: false,
        },
      ],
      totals: {
        subtotal: 1400.00,
        taxesAndFees: 450.00,
        total: 1850.00,
      },
      comparison: {
        vsPreviousSummary: 'Standard fixed bi-monthly rate.',
        percentChange: 0,
        primaryDriver: 'Fixed property-based tariff.',
        previousBillTotal: 1850.00,
        previousBillDate: '2026-05-03',
      },
      financialHealthScore: {
        score: 90,
        label: 'Excellent',
        factors: [
          { label: 'Low water cost', impact: 8, description: 'Affordable fixed bi-monthly tariff.' },
        ],
      },
      savingsSuggestions: [
        {
          id: 's-w1',
          title: 'Ensure online payment before due date to avoid 10% surcharge',
          detail: 'Late payment adds ₨ 185 penalty fee.',
          estimatedMonthlySavings: 92.50,
          categoryRelevance: 'water',
          status: 'new',
        },
      ],
      disclaimer: 'AI-generated analysis for WASA Lahore billing.',
    },
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];

export const SAMPLE_BILL_PRESETS = [
  {
    title: 'LESCO Electricity Bill (High Summer Load)',
    category: 'electricity' as BillCategory,
    providerName: 'LESCO (Lahore Electric Supply)',
    billDate: '2026-07-18',
    dueDate: '2026-08-05',
    totalAmount: 28450.00,
    lineItems: [
      { id: 'sb-e1', name: 'Base Energy Charge (520 Units)', amount: 19760.00, type: 'base_charge' as const, explanation: 'Unprotected slab power consumption.', isAnomaly: true, anomalyReason: 'Crossed 500 unit threshold into higher tariff tier.' },
      { id: 'sb-e2', name: 'Fuel Price Adjustment (FPA)', amount: 4120.00, type: 'fee' as const, explanation: 'NEPRA Monthly fuel cost adjustment.', isAnomaly: true, anomalyReason: 'Unusually high fuel cost surcharge.' },
      { id: 'sb-e3', name: 'GST & Electricity Duty (18%)', amount: 4570.00, type: 'tax' as const, explanation: 'Mandatory government taxes.', isAnomaly: false },
    ],
    sampleImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=600',
  },
  {
    title: 'SNGPL Sui Gas Bill (Domestic Slab)',
    category: 'gas' as BillCategory,
    providerName: 'SNGPL (Sui Northern Gas)',
    billDate: '2026-07-15',
    dueDate: '2026-08-02',
    totalAmount: 4820.00,
    lineItems: [
      { id: 'sb-g1', name: 'Gas Volume Usage (1.4 HM3)', amount: 3200.00, type: 'base_charge' as const, explanation: 'Domestic gas volume supplied.', isAnomaly: false },
      { id: 'sb-g2', name: 'Fixed Meter Rent & Maintenance', amount: 500.00, type: 'fee' as const, explanation: 'Fixed line connection fee.', isAnomaly: false },
      { id: 'sb-g3', name: 'General Sales Tax (GST)', amount: 1120.00, type: 'tax' as const, explanation: 'Applicable federal sales tax.', isAnomaly: false },
    ],
    sampleImage: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&q=80&w=600',
  },
  {
    title: 'PTCL Flash Fiber 50 Mbps',
    category: 'internet' as BillCategory,
    providerName: 'PTCL Flash Fiber',
    billDate: '2026-07-01',
    dueDate: '2026-07-20',
    totalAmount: 3750.00,
    lineItems: [
      { id: 'sb-p1', name: 'Flash Fiber 50 Mbps Package', amount: 2999.00, type: 'base_charge' as const, explanation: 'Monthly broadband package rate.', isAnomaly: false },
      { id: 'sb-p2', name: 'ONT Router Device Fee', amount: 250.00, type: 'fee' as const, explanation: 'Monthly hardware rental.', isAnomaly: false },
      { id: 'sb-p3', name: 'Provincial Sales Tax (19.5%)', amount: 501.00, type: 'tax' as const, explanation: 'PRA Telecom tax.', isAnomaly: false },
    ],
    sampleImage: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=600',
  },
  {
    title: 'Jazz Postpaid Monthly Connection',
    category: 'retail' as BillCategory,
    providerName: 'Jazz Postpaid',
    billDate: '2026-07-05',
    dueDate: '2026-07-22',
    totalAmount: 2490.00,
    lineItems: [
      { id: 'sb-j1', name: 'Super Postpaid 1500 Plan', amount: 1800.00, type: 'base_charge' as const, explanation: 'Unlimited Jazz calls & 40GB data.', isAnomaly: false },
      { id: 'sb-j2', name: 'Advance Tax & PST (15% + 19.5%)', amount: 690.00, type: 'tax' as const, explanation: 'Federal & Provincial withholding tax.', isAnomaly: false },
    ],
    sampleImage: 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&q=80&w=600',
  },
];

export const INITIAL_BILLS: Bill[] = DEMO_BILLS_ARCHIVE;
