import React, { useState } from 'react';
import {
  ArrowLeft,
  Sparkles,
  FileText,
  Share2,
  Download,
  Trash2,
  AlertTriangle,
  Receipt,
  CheckCircle2,
  Clock,
  Eye
} from 'lucide-react';
import { Bill, LineItem } from '../../types';
import { CATEGORY_CONFIG } from '../../lib/data';
import { formatCurrency } from '../../lib/currency';
import { useLanguage } from '../../lib/i18n';
import { ChargeBreakdown } from './ChargeBreakdown';
import { HealthScoreView } from './HealthScoreView';
import { SavingsTipsView } from './SavingsTipsView';
import { BillComparisonView } from './BillComparisonView';
import { DeleteConfirmModal } from '../common/DeleteConfirmModal';

interface AIAnalysisViewProps {
  bill: Bill;
  allBills: Bill[];
  onBack: () => void;
  onDeleteBill?: (billId: string) => void;
  onAskAboutCharge: (charge: LineItem, question: string) => Promise<string>;
}

export type AnalysisTab = 'overview' | 'breakdown' | 'score' | 'savings' | 'compare';

export const AIAnalysisView: React.FC<AIAnalysisViewProps> = ({
  bill,
  allBills,
  onBack,
  onDeleteBill,
  onAskAboutCharge,
}) => {
  const { t } = useLanguage();
  const [activeTab, setActiveTab] = useState<AnalysisTab>('overview');
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [showImageLightbox, setShowImageLightbox] = useState(false);
  const [reportDownloaded, setReportDownloaded] = useState(false);

  const categoryConfig = CATEGORY_CONFIG[bill.category] || CATEGORY_CONFIG.other;
  const analysis = bill.aiAnalysis;
  const previousBills = allBills.filter(
    (b) => b.id !== bill.id && b.category === bill.category
  );

  const handleDownloadReport = () => {
    const reportText = `BILL LENS ANALYSIS REPORT\n\nProvider: ${bill.providerName}\nAmount: ${formatCurrency(bill.totalAmount, 'PKR')}\nBill Date: ${bill.billDate}\nDue Date: ${bill.dueDate || 'N/A'}\n\nSUMMARY:\n${analysis?.plainSummary || 'No summary available.'}\n\nLINE ITEMS:\n${bill.lineItems.map(item => `- ${item.name}: ${formatCurrency(item.amount, 'PKR')} (${item.explanation})`).join('\n')}\n\nGenerated by Bill Lens AI`;
    const element = document.createElement('a');
    const file = new Blob([reportText], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `Bill_Lens_${bill.providerName.replace(/\s+/g, '_')}_Report.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    setReportDownloaded(true);
    setTimeout(() => setReportDownloaded(false), 3000);
  };

  const handleShareReport = () => {
    if (navigator.share) {
      navigator.share({
        title: `Bill Analysis: ${bill.providerName}`,
        text: `My ${bill.providerName} bill is ${formatCurrency(bill.totalAmount, 'PKR')}. Analyzed with Bill Lens AI!`,
        url: window.location.href,
      }).catch(() => {});
    } else {
      navigator.clipboard.writeText(`Bill Analysis for ${bill.providerName}: ${formatCurrency(bill.totalAmount, 'PKR')}`);
      alert('Report summary copied to clipboard!');
    }
  };

  return (
    <div className="space-y-5 pb-24 pt-2 max-w-md mx-auto animate-fade-in">
      {/* Top Header Bar */}
      <div className="flex items-center justify-between">
        <button
          type="button"
          onClick={onBack}
          className="flex items-center gap-2 px-3 py-1.5 rounded-2xl bg-white/80 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 text-xs font-black text-slate-700 dark:text-slate-200 hover:bg-slate-100 transition-all cursor-pointer shadow-xs"
        >
          <ArrowLeft className="w-4 h-4 text-teal-500" /> {t('backToDashboard')}
        </button>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleShareReport}
            className="p-2 text-slate-700 dark:text-slate-200 bg-white/80 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 rounded-2xl hover:bg-slate-100 transition-all cursor-pointer shadow-xs"
            title="Share Report"
          >
            <Share2 className="w-4 h-4 text-sky-500" />
          </button>

          <button
            type="button"
            onClick={handleDownloadReport}
            className="p-2 text-slate-700 dark:text-slate-200 bg-white/80 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 rounded-2xl hover:bg-slate-100 transition-all cursor-pointer shadow-xs"
            title="Download Report"
          >
            <Download className="w-4 h-4 text-teal-500" />
          </button>

          {onDeleteBill && (
            <button
              type="button"
              onClick={() => setShowDeleteModal(true)}
              className="p-2 text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-950/50 border border-rose-200 dark:border-rose-800 rounded-2xl hover:bg-rose-100 transition-all cursor-pointer shadow-xs"
              title="Delete Bill"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {reportDownloaded && (
        <div className="p-3 rounded-2xl bg-teal-50 dark:bg-teal-950/80 border border-teal-200 dark:border-teal-800 text-teal-800 dark:text-teal-200 text-xs font-bold flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-teal-500" /> Report downloaded successfully!
        </div>
      )}

      {/* Uploaded Bill Image Card at Top */}
      {bill.imageUrl && (
        <div className="relative overflow-hidden rounded-3xl border border-slate-200 dark:border-slate-800 bg-slate-900 shadow-md group">
          <img
            src={bill.imageUrl}
            alt={bill.providerName}
            className="w-full h-40 object-cover opacity-90 group-hover:opacity-100 transition-all duration-300"
            referrerPolicy="no-referrer"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 via-slate-950/20 to-transparent flex items-end justify-between p-4">
            <span className="text-xs font-bold text-white flex items-center gap-1.5">
              <FileText className="w-4 h-4 text-teal-400" /> Scanned Utility Document
            </span>
            <button
              type="button"
              onClick={() => setShowImageLightbox(true)}
              className="px-3 py-1 rounded-xl bg-white/20 backdrop-blur-md text-white text-[11px] font-bold flex items-center gap-1 hover:bg-white/30 transition-all cursor-pointer"
            >
              <Eye className="w-3.5 h-3.5" /> View Image
            </button>
          </div>
        </div>
      )}

      {/* Bill Overview Extracted Cards */}
      <div className="p-5 rounded-3xl bg-white/90 dark:bg-slate-900/90 backdrop-blur-md border border-slate-200/80 dark:border-slate-800 shadow-sm space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span
              className={`px-3 py-1 rounded-2xl text-xs font-black border ${categoryConfig.bgLight} ${categoryConfig.border} ${categoryConfig.color}`}
            >
              {categoryConfig.label}
            </span>
            <span className="text-xs font-bold text-slate-400 flex items-center gap-1">
              <Clock className="w-3.5 h-3.5" /> {bill.billDate}
            </span>
          </div>

          {bill.hasAnomaly && (
            <span className="px-2.5 py-1 rounded-full text-[10px] font-black bg-rose-100 text-rose-700 dark:bg-rose-950/80 dark:text-rose-300 flex items-center gap-1">
              <AlertTriangle className="w-3 h-3" /> Anomaly Flagged
            </span>
          )}
        </div>

        <div>
          <h2 className="text-xl font-black text-slate-900 dark:text-white tracking-tight">
            {bill.providerName}
          </h2>
          {bill.accountNumberMasked && (
            <span className="text-xs text-slate-400 font-medium block">
              Consumer No: {bill.accountNumberMasked}
            </span>
          )}

          <div className="flex items-baseline gap-2 mt-2 pt-2 border-t border-slate-100 dark:border-slate-800">
            <span className="text-2xl font-black text-teal-600 dark:text-teal-400">
              {formatCurrency(bill.totalAmount, 'PKR')}
            </span>
            <span className="text-xs font-bold text-slate-400">Total Due (PKR)</span>
          </div>

          {bill.dueDate && (
            <span className="text-xs font-bold text-amber-600 dark:text-amber-400 mt-1 block">
              Due Date: {bill.dueDate}
            </span>
          )}
        </div>

        {/* AI Plain Language Explanation Banner */}
        {analysis?.plainSummary && (
          <div className="p-4 rounded-2xl bg-gradient-to-br from-teal-500/10 via-sky-500/10 to-transparent border border-teal-500/30 text-slate-900 dark:text-slate-100 space-y-1">
            <span className="text-[10px] font-black uppercase tracking-widest text-teal-600 dark:text-teal-400 flex items-center gap-1.5">
              <Sparkles className="w-4 h-4" /> AI Explanation of Every Charge
            </span>
            <p className="text-xs leading-relaxed font-medium">
              {analysis.plainSummary}
            </p>
          </div>
        )}
      </div>

      {/* Sub-View Segmented Navigation Tabs */}
      <div className="flex bg-slate-100 dark:bg-slate-800/80 p-1 rounded-2xl overflow-x-auto scrollbar-none border border-slate-200/80 dark:border-slate-700/80">
        <button
          type="button"
          onClick={() => setActiveTab('overview')}
          className={`flex-1 py-2 px-3 text-[11px] font-black rounded-xl whitespace-nowrap transition-all cursor-pointer ${
            activeTab === 'overview'
              ? 'bg-gradient-to-r from-teal-500 to-sky-600 text-white shadow-xs'
              : 'text-slate-500 hover:text-slate-800 dark:hover:text-white'
          }`}
        >
          Overview
        </button>
        <button
          type="button"
          onClick={() => setActiveTab('breakdown')}
          className={`flex-1 py-2 px-3 text-[11px] font-black rounded-xl whitespace-nowrap transition-all cursor-pointer ${
            activeTab === 'breakdown'
              ? 'bg-gradient-to-r from-teal-500 to-sky-600 text-white shadow-xs'
              : 'text-slate-500 hover:text-slate-800 dark:hover:text-white'
          }`}
        >
          Charges
        </button>
        <button
          type="button"
          onClick={() => setActiveTab('score')}
          className={`flex-1 py-2 px-3 text-[11px] font-black rounded-xl whitespace-nowrap transition-all cursor-pointer ${
            activeTab === 'score'
              ? 'bg-gradient-to-r from-teal-500 to-sky-600 text-white shadow-xs'
              : 'text-slate-500 hover:text-slate-800 dark:hover:text-white'
          }`}
        >
          Health Score
        </button>
        <button
          type="button"
          onClick={() => setActiveTab('savings')}
          className={`flex-1 py-2 px-3 text-[11px] font-black rounded-xl whitespace-nowrap transition-all cursor-pointer ${
            activeTab === 'savings'
              ? 'bg-gradient-to-r from-teal-500 to-sky-600 text-white shadow-xs'
              : 'text-slate-500 hover:text-slate-800 dark:hover:text-white'
          }`}
        >
          Savings
        </button>
        <button
          type="button"
          onClick={() => setActiveTab('compare')}
          className={`flex-1 py-2 px-3 text-[11px] font-black rounded-xl whitespace-nowrap transition-all cursor-pointer ${
            activeTab === 'compare'
              ? 'bg-gradient-to-r from-teal-500 to-sky-600 text-white shadow-xs'
              : 'text-slate-500 hover:text-slate-800 dark:hover:text-white'
          }`}
        >
          Compare
        </button>
      </div>

      {/* Tab Content Display */}
      {activeTab === 'overview' && (
        <ChargeBreakdown
          lineItems={bill.lineItems}
          subtotal={analysis?.totals.subtotal || bill.totalAmount * 0.75}
          taxesAndFees={analysis?.totals.taxesAndFees || bill.totalAmount * 0.25}
          total={bill.totalAmount}
          billProvider={bill.providerName}
          currency="PKR"
          onAskAboutCharge={onAskAboutCharge}
        />
      )}

      {activeTab === 'breakdown' && (
        <ChargeBreakdown
          lineItems={bill.lineItems}
          subtotal={analysis?.totals.subtotal || bill.totalAmount * 0.75}
          taxesAndFees={analysis?.totals.taxesAndFees || bill.totalAmount * 0.25}
          total={bill.totalAmount}
          billProvider={bill.providerName}
          currency="PKR"
          onAskAboutCharge={onAskAboutCharge}
        />
      )}

      {activeTab === 'score' && analysis?.financialHealthScore && (
        <HealthScoreView scoreSnapshot={analysis.financialHealthScore} />
      )}

      {activeTab === 'savings' && analysis?.savingsSuggestions && (
        <SavingsTipsView
          suggestions={analysis.savingsSuggestions}
          currency="PKR"
        />
      )}

      {activeTab === 'compare' && (
        <BillComparisonView currentBill={bill} previousBills={previousBills} />
      )}

      {/* Image Lightbox Modal */}
      {showImageLightbox && bill.imageUrl && (
        <div className="fixed inset-0 z-50 bg-black/90 backdrop-blur-md flex items-center justify-center p-4 animate-fade-in">
          <div className="relative max-w-lg w-full max-h-[80vh] flex flex-col items-center">
            <button
              type="button"
              onClick={() => setShowImageLightbox(false)}
              className="absolute -top-12 right-0 px-4 py-2 bg-white/20 rounded-full text-white font-bold text-xs hover:bg-white/30 cursor-pointer"
            >
              Close ✕
            </button>
            <img
              src={bill.imageUrl}
              alt={bill.providerName}
              className="max-h-[75vh] w-auto object-contain rounded-2xl shadow-2xl"
              referrerPolicy="no-referrer"
            />
          </div>
        </div>
      )}

      {/* AI Legal Disclaimer */}
      <div className="p-4 rounded-2xl bg-slate-100 dark:bg-slate-900/60 text-[11px] text-slate-500 dark:text-slate-400 text-center leading-normal font-medium border border-slate-200/60 dark:border-slate-800">
        {analysis?.disclaimer ||
          'AI-generated analysis for informational guidance. Tariff rates governed by NEPRA / OGRA.'}
      </div>

      <DeleteConfirmModal
        isOpen={showDeleteModal}
        itemName={bill.providerName}
        onConfirm={() => {
          if (onDeleteBill) {
            onDeleteBill(bill.id);
            onBack();
          }
        }}
        onClose={() => setShowDeleteModal(false)}
      />
    </div>
  );
};
